name : My First github Action

on : push

jobs:
    first-task:
      runs-on : ubuntu-latest
      steps:
        - name : npm installing
          run : |
                echo " Hi"
                exit 1
